config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'tweets#home'
  get 'reply', to: 'tweets#reply'

  resources :users, param: :username do
    member do
      resource :displaypic
      get :following, :followers
    end
    # , only: [:show, :new, :create] do
    #   member do
    #     patch :set_as_primary
    #   end
    # end
  end

  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :tweets do
    collection do
      get 'search'
    end
  end
  # , only: [:show] do
  #   resource :picture, only: [:show, :new, :create]
  # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
  belongs_to :user

  validates :user_id, :tweet_id, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :tweets, :uniq => true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_and_belongs_to_many :tags, :uniq => true

  max_body_length = 140

  validates :body, :user_id, presence: true
  validates :body, length: {minimum: 1, maximum: max_body_length}

  def self.search(search)
    where("body ILIKE ?", "%#{search}%")
  end

  def self.save_hashtag(tweet)
    body = tweet.body
    body.scan(/(?<=\s|^)#(\w*[A-Za-z_]+\w*)/).flatten.each do |tag|
      tweet.tags.create(body: tag.downcase)
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                    foreign_key: "follower_id",
                                    dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                  foreign_key: "followed_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed #source: name of the column in Relationships table
  has_many :followers, through: :passive_relationships, source: :follower
  
  validates :username, length: { minimum: 6 }
  validates :username, uniqueness: { case_sensitive: false }

  # Follows a user.
  def follow(other_user)
    following.push(other_user)
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :password, :email, :avatar])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  # User needs to login before doing the following actions
  before_action :authenticate_user!

  before_action :set_tweet

  def create
    @like = current_user.likes.build(tweet_id: @tweet.id)
    @like.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(tweet_id: @tweet.id, user_id: current_user.id)
    @like.delete
    redirect_back(fallback_location: root_path)
  end
  
  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  # def index
  # end
  
  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.js
    end
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # Find params before the following actions
  before_action :set_tweet, only: [:show, :destroy]
  # User needs to login before doing the following actions
  before_action :authenticate_user!

  def home
    @tweet = current_user.tweets.build(new_tweet_params)
    @tweets = Tweet.all
  end

  def search
    @search = params[:search]

    if params[:search]
      @tweets = Tweet.search(params[:search])
    end
  end

  def show
    @tweet_replies = Tweet.where(reply_id: @tweet.id)
  end

  def reply
    redirect_to root_path(reply_params)
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)
    @tweets = Tweet.all

    respond_to do |format|
      if @tweet.save
        Tweet.save_hashtag(@tweet)
        format.js
      else
        format.js
      end
    end
  end

  def destroy
    @tweet.destroy
    redirect_to root_path
  end

  private


  def tweet_params
    params.require(:tweet).permit(:body, :reply_id, :image)
  end

  def new_tweet_params
    params.permit(:body, :reply_id, :image)
  end

  def reply_params
    {:reply_id => params[:reply_to_tweet_id], :body => "@" + User.find(params[:reply_to_user_id]).username + " "}
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # User needs to login before doing the following actions
  before_action :authenticate_user!

  before_action :set_user
  # def index
  #   @users = User.all
  # end

  def show
    @tweets = @user.tweets
    @tweets_count = @tweets.count

    @likes = @user.likes
    @likes_count = @likes.count
    @likes.each do |like|
      tweet = Tweet.find(like.tweet_id)
      if tweet.user_id == @user.id
        @likes_count -= 1
      end
    end

    @following = @user.following.count
  end

  def following
    @title = "Following"
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @users = @user.followers
    render 'show_follow'
  end

  private

  def set_user
    @user = User.find_by(username: params[:username])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_searchbar.html.erb
<%= form_tag search_tweets_path, method: :get, class: "navbar-form navbar-right" do %>
    <div class="form-group">
    <%= text_field_tag :search, params[:search], placeholder: "I'm looking for...", class: 'form-control' %>
    <%= submit_tag "Search", :name => nil, class: 'btn btn-default' %>
     <span class="search-tm pull-right">Powered by SabrinaSearch&trade;</span>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MondayClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

        <nav class="navbar navbar-inverse">
          <div class="container">
            <div class="navbar-header">
              <%= link_to "MondayClone", root_path, class: "navbar-brand" %>
            </div>
            <ul class="nav navbar-nav">
              <% if user_signed_in? == false %>
                <li><%= link_to 'Sign up', new_user_registration_path%></li>
                <li><%= link_to 'Sign in', new_user_session_path %></li>
              <% else %>
                <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                <li class="navbar-text", style="text-align: right">Logged in as: <span><%= link_to current_user.username, user_path(current_user.username) %></span></li>
              <% end %>
              <%= render partial: 'searchbar' %>
            </ul>
          </div>
          <!-- <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p> -->
        </nav>

    <%= yield %>
  </body>
</html>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= j render partial: 'users/unfollow' %>");
$("#followers").html("<%= @user.followers.count %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= j render partial: 'users/follow' %>");
$("#followers").html("<%= @user.followers.count %>");

app/views/tweets/_avatar.html.erb
<% if current_user.avatar? %>
  <%= image_tag current_user.avatar.url, size: "100x100",class: "img-circle" %>
<% else %>
  <%= image_tag "starfish.png", size: "100x100",class: "img-circle" %>
<% end %>

app/views/tweets/_tweetbox.html.erb
<%= form_for @tweet, remote: true, html: { id: "tweetbox" } do |t| %>
  <div class="form-group">
    <%= t.label "Compose Tweet", class: "h3" %>
    <%= t.text_area :body, class: "form-control", placeholder: "Type your tweet here..", style: "height:100px" %>
    <div class="countdown"></div>
    <class="create-button"><%= t.submit "Create", class: "btn btn-success pull-right"%>

    <%= t.label "Upload image", class: "h5" %>
    <%= t.file_field :image %>

    <%= t.hidden_field :reply_id %>
  </div>
<% end %>

app/views/tweets/_tweets.html.erb
<% @tweets.reverse_each do |tweet| %>
  <div class="panel panel-default">
      <div class="panel-heading">
        <% if tweet.user.avatar? %>
          <%= image_tag tweet.user.avatar.url, size: "25x25",class: "img-circle" %>
        <% else %>
          <%= image_tag "starfish.png", size: "25x25",class: "img-circle" %>
        <% end %>
        <%= link_to "@"+tweet.user.username, user_path(tweet.user.username), class: "panel-title" %>
      </div>

      <div class="panel-body">
        <div class="row">
          <div class="col-xs-12">
            <%= tweet.body %>
            <br>
            <% tweet.tags.map(&:body).each do |hashtag| %>
            <span class="hashtag label label-warning"><%=link_to hashtag, search_tweets_path(:search => "#"+hashtag) %></span>
            <% end %>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12">
            <div class="like pull-right">
              <% if Like.find_by(tweet_id: tweet.id, user_id: current_user) != nil %>
                <%= link_to like_path(id: tweet, path: "tweet"), method: :delete do %>
                  <span class="glyphicon glyphicon-heart"></span>
                <% end %>
              <% else %>
                <%= link_to likes_path(id: tweet, path: "tweet"), method: :post do %>
                  <span class="glyphicon glyphicon-heart-empty"></span>
                <% end %>
              <% end %>

              <% if tweet.likes.count > 0 %>
                 <span class="h6"><%= tweet.likes.count %></span>
              <% else %>
                 &nbsp;
              <% end %>
            </div>
          </div>
        </div>
      </div>
      
        <% if tweet.image? %>
          <div>
            <button type="button" class="btn btn-link btn-block center-block" data-toggle="collapse" data-target="#tweet-image">Show Image</button>
          </div>
          <div id="tweet-image" class="collapse">
            <%= image_tag tweet.image.url, class: "home-tweet" %>
          </div>
        <% end %>
      
      <div class="panel-footer">
        <% if current_user == tweet.user %>
          <%= link_to "Delete", tweet_path(tweet), method: :delete %>
        <% else %>
          <%= link_to "Reply", reply_path(:reply_to_tweet_id => tweet.id, :reply_to_user_id => tweet.user.id)%>
        <% end %>
        <%= link_to tweet.created_at.strftime("%c"), tweet_path(tweet), class: "pull-right" %><br>
      </div>
  </div>
<% end %>

app/views/tweets/create.js.erb
if("<%= @tweet.id %>") {
  $(".tweets").html("<%= j render partial: 'tweets' %>");
  $("#tweetbox").find("textarea").val("");
  $("#tweetbox").find("#tweet_reply_id").val("");
  $('.countdown').text('140 characters remaining.');
} else {
  $("tweetbox").html("<%= j render partial: 'tweetbox' %>")
}

app/views/tweets/home.html.erb
<div class="container">
  <div class="row">
    <!-- User profile section, need to show follwers and following count -->
    <div class="col-md-3">
      <div class="row">
        <div class="col-xs-6">
          <h3><%= current_user.username %></h3>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6">
          <%= render partial: "avatar" %>
        </div>
        <div class="col-xs-6">
          <!-- Following count-->
          <div class="row">
            <div class="col-xs-12 following-count">
              <%= current_user.following.count  %> <%= link_to "Following", following_user_path(current_user.username) %>
            </div>
          </div>
          <!-- Followers count -->
          <div class="row">
            <div class="col-xs-12 following-count">
              <span id="followers"><%= current_user.followers.count %></span> <%= link_to "Followers", followers_user_path(current_user.username) %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Compose tweet textbox -->
    <div class="col-md-6 tweetbox">
      <%= render partial: "tweetbox" %>
    </div>
  </div>
    <!--Showing list of tweets  -->
  <div class="row">
    <div class="col-md-6 col-md-offset-3 tweets">
        <%= render partial: "tweets" %>
    </div>
  </div>

</div>

app/views/tweets/search.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 tweets">
      <h2>Search results for "<%= @search %>":</h2>
      <%= render partial: 'tweets' %>
      <% if @tweets.blank? %>
        <h4>Sorry, we couldn't find any tweets containing "<%= params[:search] %>".</h4>
      <% end %>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <h3><%= @tweet.body %>
    <% if @tweet.image? %>
      <%= image_tag @tweet.image.url, class: "home-tweet" %>
    <% end %></h3><br>
  <% if @tweet_replies.count > 0 %>
    <h4>Replies (<%= @tweet_replies.count %>)</h4>
      <% @tweet_replies.each do |reply| %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= link_to "@"+reply.user.username, user_path(reply.user), class: "panel-title" %>
          </div>
          <div class="panel-body">
            <%= reply.body %>
            <% if reply.image? %>
            <%= image_tag reply.image.url, class: "home-tweet" %>
            <% end %>
          </div>
          <div class="panel-footer">
            <% if current_user == reply.user %>
              <%= link_to "Delete Tweet", tweet_path(reply), method: :delete%>
              <%= link_to reply.created_at.strftime("%c"), tweet_path(reply), class: "pull-right" %>
            <% else %>
              <%= link_to reply.created_at.strftime("%c"), tweet_path(reply), class: "pull-right" %><br>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <h4>No Replies</h4>
    <% end %>
  </div>
</div>

app/views/users/_avatar.html.erb
<% if @user.avatar? %>
  <%= image_tag @user.avatar.url, size: "100x100",class: "img-circle" %>
<% else %>
  <%= image_tag "starfish.png", size: "100x100",class: "img-circle" %>
<% end %>

app/views/users/_favourite.html.erb
<h3>Favourite Tweets (<%= @likes_count %>)</h3>
<% if @likes_count > 0 %>
  <% @likes.reverse_each do |like| %>      
    <% tweet = Tweet.find(like.tweet_id) %>
    <% if tweet.user_id != @user.id %>
      <%= render partial: "tweetrow", locals: {tweet: tweet} %>
    <% end %>
  <% end %>
<% else %>
  <div class="panel panel-default">
    <div class="panel-body">
      No favourite tweet
    </div>  
  </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary btn-block" %>
<% end %>

app/views/users/_owntweets.html.erb
<h3>Own Tweets (<%= @tweets_count %>)</h3>
<% if @tweets_count > 0 %>
  <% @tweets.reverse_each do |tweet| %>
    <%= render partial: "tweetrow", locals: {tweet: tweet} %>
  <% end %>
<% else %>
  <div class="panel panel-default">
    <div class="panel-body">
      No own tweets
    </div>  
  </div>
<% end %>
<hr>

app/views/users/_tweetrow.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <% if tweet.user.avatar? %>
      <%= image_tag tweet.user.avatar.url, size: "25x25",class: "img-circle" %>
    <% else %>
      <%= image_tag "starfish.png", size: "25x25",class: "img-circle" %>
    <% end %>
    <%= link_to "@"+tweet.user.username, user_path(tweet.user.username), class: "panel-title" %>
  </div>

  <div class="panel-body">
    <div class="row">
      <div class="col-xs-12">
        <%= tweet.body %>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">
        <div class="like pull-right">
          <% if Like.find_by(tweet_id: tweet.id, user_id: current_user) != nil %>
            <%= link_to like_path(id: tweet, path: "tweet"), method: :delete do %>
              <span class="glyphicon glyphicon-heart"></span>
            <% end %>
          <% else %>
            <%= link_to likes_path(id: tweet, path: "tweet"), method: :post do %>
              <span class="glyphicon glyphicon-heart-empty"></span>
            <% end %>
          <% end %>

          <% if tweet.likes.count > 0 %>
             <span class="h6"><%= tweet.likes.count %></span>
          <% else %>
             &nbsp;
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <% if tweet.image? %>
    <div>
      <button type="button" class="btn btn-link btn-block center-block" data-toggle="collapse" data-target="#tweet-image">Show Image</button>
    </div>
    <div id="tweet-image" class="collapse">
      <%= image_tag tweet.image.url, class: "home-tweet" %>
    </div>
  <% end %>
  
  <div class="panel-footer">
    <% if current_user == tweet.user %>
      <%= link_to "Delete", tweet_path(tweet), method: :delete %>
    <% else %>
      <%= link_to "Reply", reply_path(:reply_to_tweet_id => tweet.id, :reply_to_user_id => tweet.user.id)%>
    <% end %>
    <%= link_to tweet.created_at.strftime("%c"), tweet_path(tweet), class: "pull-right" %><br>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), remote: true, method: :delete) do |f| %>
  <%= f.submit "Unfollow", class: "btn-primary btn-block" %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3">
      <div class="row">
        <div class="col-xs-6">
          <h3><%= @user.username %></h3>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6">
          <%= render partial: "avatar" %>
        </div>
        <div class="col-xs-6">
          <!-- Following count-->
          <div class="row">
            <div class="col-xs-12 following-count">
            <%= @following %> <%= link_to "Following", following_user_path(@user.username) %>
            </div>
          </div>
          <!-- Followers count -->
          <div class="row">
            <div class="col-xs-12 following-count">
            <span id="followers"><%= @user.followers.count %></span> <%= link_to "Followers", followers_user_path(@user.username) %>
            </div>
          </div>
          <!-- Follow button -->
          <div class="row">
            <div class="col-xs-12">
              <% if user_signed_in? %>
                <% if current_user != @user %>
                  <div id="follow_form" class="pull-center">
                    <% if current_user.following?(@user) %>
                      <%= render partial: "unfollow" %>
                    <% else %>
                      <%= render partial: "follow" %>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="col-md-6">
      <%= render partial: "owntweets" %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render partial: "favourite" %>
    </div>
  </div>
  
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="container">
  <div class="row">
    <aside class="col-md-4">
      <h3><%= @user.username %></h3>
      <div><%= link_to "View my profile", user_path(@user.username) %></div>
      <b>Tweets:</b> <%= @user.tweets.count %>
    </aside>
    <div class="col-md-8">
      <h3><%= @title + " " %>(<%= @users.count %>)</h3>
      <% if @users.any? %>
        <ul>
          <% @users.each do |user| %>
            <li><%= link_to user.username, user_path(user.username) %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>